In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt
from matplotlib import animation, rc
import seaborn as sns
from IPython.display import HTML
from matplotlib.widgets import Slider

## ISING MODEL INTRODUCTION

#### Task 1: Creating initial grid 

First let's create the system of spins. We can do that by assigning each point on the two-dimensional grid with the number: 1 (spin up) or -1 (spin down). Creating an "empty" grid of size L = 10, can be done with following piece of code:

In [2]:
L = 10

grid = np.zeros((L, L))

Variable grid is now an array of zeros. Try to assign to each site of this array either +1 or -1, by using "for" loops:

In [3]:
for i in range(L):
    for j in range(L):
        grid[i, j] = 1 - 2 * np.random.randint(2)   
                                         # this is how you can access i-th row and j-th column of the grid. Try to call a function 
                                         # (on the right side of assignment) that will randomly return either -1 or 1.

Great! Let's check out if grid has now the +1 and -1 as its values:

In [4]:
print(grid)

[[ 1. -1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1. -1. -1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1. -1.  1.  1. -1.  1.  1.]
 [-1. -1.  1. -1. -1.  1.  1.  1.  1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.  1. -1.  1. -1. -1.]
 [ 1.  1. -1.  1.  1. -1. -1.  1.  1.  1.]
 [ 1. -1.  1. -1. -1. -1.  1.  1.  1. -1.]]


#### Task 2: Writing the function that "flips" spins

For our algorithm to work, we need a way to flip single spins on a given position of the lattice. Let's write a function that will do that. It should take as an input the position of the spin. It should check what is a current value of the spin at that point and change it accordingly.

In [5]:
def flip_spin(i, j):
    if grid[i, j] == 1:
        grid[i, j] = -1
    else:
        grid[i, j] = 1

#### Task 3: Writing the function that calculates energy of the grid

We will also need a function that will calculate the energy of our grid configuration. This is important, as we will need to check the difference between energy of our grid before and after the spin flip.

In [6]:
J = -1

def calculate_energy():
    en = 0
    for i in range(L):
        for j in range(L):
            for k in range(4):
                en += J * grid[i, j] * (grid[(i+1)%L, j] + grid[i-1, j] + grid[i, (j+1)%L] + grid[i, j-1])
    return en          

#### Task 4: Writing the function that evolves our system

Last function will handle evolving our system, that is flipping spins randomly and accepting or rejecting new configuration according to change in energy.

In [7]:
T = 1

def update_system():
    i = np.random.randint(L)
    j = np.random.randint(L)
    en_old = calculate_energy()
    flip_spin(i, j)
    en_new = calculate_energy()
    
    if np.exp(-(en_new - en_old) / T) < np.random.rand():
        flip_spin(i, j)
        
        
%matplotlib qt 



fig, ax_lst = plt.subplots()

im = ax_lst.imshow(grid)



while True:
    update_system()
    im.set_data(grid) 
    plt.pause(0.001)

KeyboardInterrupt: 